version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: gem-approval-backend
    ports:
      - "8000:8000"
    volumes:
      # Persist Chrome data and logs using named volumes
      - logs:/app/logs
      - chrome_data:/app/chrome_data
      - bot_data:/app/bot_data.db
    environment:
      - POST_URL=${POST_URL}
      - FACEBOOK_USERNAME=${FACEBOOK_USERNAME}
      - FACEBOOK_PASSWORD=${FACEBOOK_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - COMMENT_BOX_XPATH=${COMMENT_BOX_XPATH}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost,http://localhost:80,http://frontend}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    container_name: gem-approval-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  # Optional: Add a database service if needed
  # database:
  #   image: sqlite:latest
  #   container_name: gem-approval-db
  #   volumes:
  #     - ./data:/data
  #   restart: unless-stopped

volumes:
  chrome_data:
  logs:
  bot_data:

networks:
  default:
    name: gem-approval-network